### ISSUE TITLE
Horizon error connecting to kafka

### ISSUE THREAD

**Issue by bmgante** [opennms-forge/ansible-opennms#51]
Hello,

Tried to enable horizon core to connect to the kafka created by this ansible playbook.

 [kafka-consumer-0] o.a.k.c.NetworkClient: [Consumer clientId=consumer-OpenNMS-5, groupId=OpenNMS] Node 1 disconnected. 

WARN [kafka-consumer-15] 
o.a.k.c.NetworkClient: [Consumer clientId=consumer-OpenNMS-33, groupId=OpenNMS] Connection to node 1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available  

This is my horizon core kafka.properties:

```
org.opennms.activemq.broker.disable=true
org.opennms.core.ipc.strategy=kafka
org.opennms.core.ipc.sink.initialSleepTime=60000
org.opennms.core.ipc.kafka.bootstrap.servers=a.b.c.d:9092 
```

The kafka is in the same VM as minion. But do not understand why it is trying to connect to localhost/127.0.0.1:9092 if i have the correct kafka ip in the config.

**Comment by ProjectJYL** [comment]
@bmgante Is `a.b.c.d` matching the hostname/ip of the interface where the broker is listening on? As far as I understand, it should be exactly what's in the advertised listeners configuration. If it's a hostname, it should be a resolvable hostname for the minion. You can find the explanation about listeners such as this [article](https://www.confluent.io/blog/kafka-listeners-explained/).

**Comment by bmgante** [comment]
Indeed, the problem was the advertised listener which was not properly set. Thanks
